const labels = {
  SYSTEM_MANAGE: '系统设置',
  MENU_ADD: '目录新增',
  MENU_EDIT: '目录编辑',
  NO_DATA: '暂无数据',
  LOAD_FAIL: '加载失败',
  RESPONSE_RESULT_EXCEPTION: '请求出现错误，请稍后再试',
  NET_ERROR: '网络请求失败',
  USER_ADD: '用户新增',
  USER_EDIT: '用户编辑',
  SAVE_SUCCESS: '保存成功',
  SAVE_FAIL: '保存失败',
  SURE_DELETE: '真的删除吗?',
  DELETE_SUCCESS: '删除成功',
  DELETE_FAIL: '删除失败',
  QUERY_FAIL: '查询失败',
  GET_DATA_FAIL: '获取数据失败',
  GET_DATA_SUCCESS: '获取数据成功',
  OPERATE_FAIL: '操作失败',
  OPERATE_SUCCESS: '操作成功',
  VERIFY_CODE_ERROR: '验证码错误',
  OK: '确定定',
  CANCEL: '取消',
  DELETE: '删除',
  UPLOAD: '上传',
  UPLOAD_FILE_FAIL: '上传文件失败',
  SELECT_FILE: '选择文件',
  FILE_TRANSFORM_FAIL: '文件转换失败',
  SAVE: '保存',
  MAX_LENGTH_ZH_WARNING: '字符数量已超出最大限制！最多可输入中文字符数：',
  MAX_LENGTH_WARNING: '字符数量已超出最大限制！最多可输入字符数：',
  ADD: '新增',
  EDIT: '修改',
  HINT: '提示',
  PRINTING: '打印',
  EXPORT_SUCCESS: '导出成功',
  EXPORT_FAIL: '导出失败',
  IMPORT_SUCCESS: '导入成功',
  IMPORT_FAIL: '导入失败',
  CONFIRM_LOGINOUT: '真的要注销登录吗?',
  ERROR: '错误',
  IMAGE_CONVERT_FAIL: '图片转换失败',
  RESET_PASSWORD_SUCCESS: '重置密码成功！',
  GET_ROLE_DATA_FAIL: '获取角色数据失败',
  RULES_ERROR:'校验失败',
  ELIMINATE_SUCCESS:'剔除成功',
  ELIMINATE_FAIL:'剔除失败',
  AUDIT_SUCCESS: '审核成功',
  AUDIT_ERROR: '审核失败 ',
  APPLY_SUCCESS: '申请成功',
  APPLY_ERROR: '申请失败',
  IGNORE_ERROR: '忽略失败',
  IGNORE_SUCCESS: '忽略成功'
}
export default labels
